// <auto-generated />
using GridironIQ.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridironIQ.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910004835_AddPlayerRelationshipsAndSeedData")]
    partial class AddPlayerRelationshipsAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridironIQ.Core.Entities.GameLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("FantasyPoints")
                        .HasColumnType("double precision");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PassingYards")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceivingYards")
                        .HasColumnType("integer");

                    b.Property<int>("RushingYards")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Touchdowns")
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FantasyPoints = 18.399999999999999,
                            Opponent = "SEA",
                            PassingYards = 0,
                            PlayerId = 1,
                            ReceivingYards = 42,
                            RushingYards = 86,
                            Season = 2025,
                            Touchdowns = 1,
                            Week = 1
                        });
                });

            modelBuilder.Entity("GridironIQ.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christian McCaffrey",
                            Position = "RB",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trevor Lawrence",
                            Position = "QB",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "DeVonta Smith",
                            Position = "WR",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cooper DeJean",
                            Position = "CB",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jalen Carter",
                            Position = "DT",
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("GridironIQ.Core.Entities.Projection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<double>("ProjectedPoints")
                        .HasColumnType("double precision");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Projections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayerId = 1,
                            ProjectedPoints = 19.199999999999999,
                            Season = 2026,
                            Week = 2
                        });
                });

            modelBuilder.Entity("GridironIQ.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "SF",
                            Conference = "NFC",
                            Division = "West",
                            Name = "San Francisco 49ers"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "JAX",
                            Conference = "AFC",
                            Division = "South",
                            Name = "Jacksonville Jaguars"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "PHI",
                            Conference = "NFC",
                            Division = "East",
                            Name = "Philadelphia Eagles"
                        });
                });

            modelBuilder.Entity("GridironIQ.Core.Entities.GameLog", b =>
                {
                    b.HasOne("GridironIQ.Core.Entities.Player", "Player")
                        .WithMany("GameLogs")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GridironIQ.Core.Entities.Player", b =>
                {
                    b.HasOne("GridironIQ.Core.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GridironIQ.Core.Entities.Projection", b =>
                {
                    b.HasOne("GridironIQ.Core.Entities.Player", "Player")
                        .WithMany("Projections")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GridironIQ.Core.Entities.Player", b =>
                {
                    b.Navigation("GameLogs");

                    b.Navigation("Projections");
                });

            modelBuilder.Entity("GridironIQ.Core.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
