<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GridironIQ.Core\GridironIQ.Core.csproj" />
    <ProjectReference Include="..\GridironIQ.Services\GridironIQ.Services.csproj" />
    <ProjectReference Include="..\GridironIQ.Infrastructure\GridironIQ.Infrastructure.csproj" />
  </ItemGroup>

</Project>
